{% set version = "2.3.1" %}
{% set hash = "81a3b75c6b5cfdf29bb660a7b87a99be184d70a78093651e23bc886e46223d45" %}

package:
  name: capytaine
  version: {{ version }}

source:
  url: https://github.com/capytaine/capytaine/archive/refs/tags/v{{ version }}.tar.gz

  # # For dry-run before making the release
  # url: https://github.com/capytaine/capytaine/archive/refs/heads/master.tar.gz

  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - capytaine = capytaine.ui.cli:main

requirements:
  build:
    # uses m2w64 toolchain on windows, see conda_build_config.yaml
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - numpy
    - meson-python
    - charset-normalizer
    - llvm-openmp  # [osx]
    - distutils-activate-mingw  # [win]
  run:
    - python
    - scipy
    - pandas
    - xarray
    - rich
    - llvm-openmp  # [osx]

test:
  imports:
    - capytaine
  requires:
    - pytest
    - pip
    # one test depends on implicit scalar conversion that was removed
    - numpy <2.4
  source_files:
    - pytest/*.py
    - pytest/**/*
  commands:
    - pytest
    - capytaine --help

about:
  home: https://github.com/capytaine/capytaine
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python-based linear potential flow solver based on Nemoh

extra:
  recipe-maintainers:
    - mancellin
